# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5255f38ef6fea3f983ac620206dd1a957bbf73f46003be5abe2d3aca2ebf7934e407229c99dcc7043b7840c6287688f1c10c802cbbbfdfbea3113eb1272e5499

test:
  secret_key_base: cc4a21e8073016d020d5dc31878b6f90b9cea18e6f0d9be26dba5167168cfe0db558fbfef19c70ce125431e52309d539cfb2c4471c63c7fb5a181c3437cc186e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
